### ISSUE TITLE
Decisión de tecnologías y prototipo de web scraper

### ISSUE THREAD

**Issue by dpuertamartos** [dpuertamartos/big_data_tfm#1]
La primera idea del proyecto consiste en un proceso de ETL de datos inmobiliarios provenientes de idealista.com. Los cuales serán posteriormente utilizados en un modelo de aprendizaje automático que los clasificará o agrupará.

En la reunión del 27/06/2023 se esbozaron las tareas del primer bloque:

1. Se hará un primer estudio y propuesta de las tecnologías a usar
2. Se hará un prototipo de webscraper para idealista.com

**Comment by dpuertamartos** [comment]
Se ha hecho un prototipo con scrapy para pisos.com, idealista.com tiene una política extremadamente estricta para scrapping. He sido incapaz de utilizar ninguna herramienta, ni siquiera imitando un browser con sellenium. 

En cambio pisos.com es mucho más permisivo e incluso se puede scrapear sin infrigir su robots.txt

**Comment by dpuertamartos** [comment]
Se ha añadido un readme con una propuesta de una arquitectura temprana

**Comment by dpuertamartos** [comment]
Como comentario ante la propuesta de la reunión del 27/06/23 de usar zenhub, me he encontrado que es de pago y solo tiene un trial de 14 días.

**Comment by alvarag** [comment]
Se puede conseguir Zenhub gratuito para estudiantes con "Github for students", no sé si lo tienes activado
