### ISSUE TITLE
Inicio documentación análisis de datos - Primera implementación de modelos

### ISSUE THREAD

**Issue by dpuertamartos** [dpuertamartos/big_data_tfm#8]

**Comment by alvarag** [comment]
Comentarios en el pdf adjunto
[ETL_y_aprendizaje_automático_sobre_inversiones_inmobiliarias-AAG.pdf](https://github.com/dpuertamartos/big_data_tfm/files/13278425/ETL_y_aprendizaje_automatico_sobre_inversiones_inmobiliarias-AAG.pdf)
